import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { CartProvider } from "./context/CartContext";
import Navigation from "./components/nav/Header";
import Footer from "./components/footer/Footer";
import Header from "./components/nav/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quick Ecomm",
  description: "Generated by Abhijith",
  keywords: ["upcode","Professional training"]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Header />
          <main style={{ minHeight: "80vh", padding: "20px" }}>{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
